In [1]:
from utils import *
from utils.slugify import slugify

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as plticker

import pandas as pd
import re 

%matplotlib inline

In [2]:
def search_word(df,search_column,palavra):
    new_df = df.loc[df[search_column].str.contains(palavra,flags=re.IGNORECASE)]
    return new_df

In [10]:
df1 = pd.read_csv("ocean_online_events_second_year.csv")
df2 = pd.read_csv("cursos_ofertados_1_ano_com_trilha.csv")

In [11]:
df_excluded_data = search_word(df1,"eve_title","Ocean|Startup|Demoday|Empreendedorismo|Meetup")
df_excluded_data["eve_title"].unique()

In [12]:
df_excluded_data.shape

(5872, 26)

In [13]:
df1.drop(df_excluded_data.index,axis=0,inplace=True)

In [14]:
df1.shape

(82930, 26)

In [15]:
df1["eve_title"].unique()

array(['Tizen: Ferramenta e Ambiente de Desenvolvimento',
       'Introdução a Análise de Dados Geográficos com Python',
       'Tizen: Desenvolvimento de aplicação para ambiente Tizen',
       'Introdução à Internet das Coisas',
       'Laboratório de IoT com Arduino',
       'Programando para web com Python, CSS e HTML (Parte 1)',
       'Programando para web com Python, CSS e HTML (Parte 2)',
       'Desenvolvimento Ágil - DevOps Docker',
       'Desenvolvimento Ágil: DevOps GIT',
       'Introdução ao Backend com NodeJs e Express',
       'Laboratório de IoT com Raspberry Pi',
       'Laboratório de Backend com NodeJs e Express',
       'Oficina de Usabilidade', 'Oficina: Design Thinking',
       'Linguagem Python: aprendendo a linguagem (Parte1)',
       'Linguagem Python: aprendendo a linguagem (Parte 2)',
       'Linguagem Python: aprendendo a linguagem (Parte 3)',
       'Introdução ao Frontend Web com React',
       'Introdução ao Deep Learning com Python e Keras (Parte 1)',
       'Introdução ao Deep Learning com Python e Keras (Parte 2)',
       'Palestra: Assistente Virtual de Voz em Bixby - Trazendo Inteligência à Interface',
       'Tópicos de UX para Design de Serviços',
       'Integrando os serviços de backend na nuvem',
       'Tópicos de UX para IA: Experiências Ominicanal',
       'Laboratório de Frontend Web com React',
       'Mineração de Opinião com Python', 'Android: Introdução',
       'Android: Laboratório', 'Web Scraping com Python (Parte 1)',
       'Web Scraping com Python (Parte 2)',
       'Web Scraping com Python (Parte 3)', 'Introdução ao Blockchain',
       'Ciência de Dados: Visualização de Dados com Python (Parte 1)',
       'Ciência de Dados: Visualização de Dados com Python (Parte 2)',
       'Jogos Digitais: Jogo 2D com Unity (Parte 1)',
       'Jogos Digitais: Jogo 2D com Unity (Parte 2)',
       'Introdução a Análise de Dados Geográficos com Python (Parte 1)',
       'Introdução a Análise de Dados Geográficos com Python (Parte 2)',
       'Introdução a Análise de Dados Geográficos com Python (Parte 3)',
       'Introdução aos dispositivos Wearables',
       'Oficina: Ferramentas de Suporte a Programação para Blockchain',
       'Ciência de Dados: Fundamentos de análise de dados com Orange',
       'Tópicos em Indústria 4.0',
       'Laboratório de Backend e Banco de Dados com MongoDB',
       'Backend com NodeJs e Express (Parte 1)',
       'Backend com NodeJs e Express (Parte 2)',
       'Oficina: Programação de uma aplicação para Blockchain',
       'Consultando Bases SQL com Python (Parte 1)',
       'Consultando Bases SQL com Python (Parte 2)',
       'Introdução ao Frontend Web com React (Parte 1)',
       'Introdução ao Frontend Web com React (Parte 2)',
       'Introdução a Internet das Coisas',
       '(Jornada Android) Android: Introdução',
       '(Jornada Android) Android: Laboratório',
       '(Jornada Android) Android: GPS com Google Maps',
       '(Jornada Android) Android: Webservices com Retrofit e Imagens com Glide',
       '(Jornada Android) Android: Listas com RecyclerView e Multithread',
       '(Jornada Android) Android: Banco de Dados com Android Room',
       '(Jornada Android) Android: Push Notification com Firebase',
       '(Jornada Android) Android: Jetpack e Arquitetura',
       'Ciência de Dados: Fundamentos de Análise de Dados com Orange',
       'Teste de email',
       'Linguagem Python: aprendendo a linguagem (Parte 1)',
       'Jogos Digitais: Introdução',
       'Realidade Virtual, Aumentada e Mista: Introdução ao XR',
       'Frontend Web com ReactJS: Introdução (Parte 1)',
       'Frontend Web com ReactJS: Introdução (Parte 2)',
       'Palestra: Introdução ao Blockchain',
       'Desenvolvimento Ágil - DevOps GIT',
       'Frontend Web com ReactJS - Integração com Backend (Parte 1)',
       'Frontend Web com ReactJS - Integração com Backend (Parte 2)',
       'IA e IoT para Cidades Inteligentes',
       'IOT: Laboratório de IOT com Arduino', 'Introdução à IoT',
       'IOT: Laboratório de IoT com Raspberry Pi',
       'IOT: Laboratório de IoT em Cloud',
       'Módulo 4: Avançando com Deep Learning',
       'Deep Learning: Introdução com Keras e Python (Parte 1)',
       'Oficina de Jogos 2D com Unity (Parte 1)',
       'Oficina de Jogos 2D com Unity (Parte 2)',
       'Oficina de Jogos 2D com Unity (Parte 3)',
       'Deep Learning: Introdução com Keras e Python (Parte 2)',
       'Tópicos de UX para IA: Experiências Omnicanal',
       'Oficina de Realidade Aumentada',
       'Jogos Digitais: Jogo 3D com Unity (Parte 1)',
       'Palestra: T1 - Introdução ao Tizen',
       'Programando para web com Python, CSS e HTML (Parte 3)',
       'Jogos Digitais: Jogo 3D com Unity (Parte 2)',
       ' Web Scraping com Python (Parte 1)',
       'Aprendendo a programar do zero (Parte 1)',
       'Aprendendo a programar do zero (Parte 2)',
       'Interface de jogos para telas dobráveis Games, AR and VR',
       'Introdução aos Jogos Digitais',
       'Criação de Jogos 2D com Unity (Parte 1)',
       'Palestra: Introdução ao Blockchain ',
       'Criação de Jogos 2D com Unity (Parte 2)',
       'Modelagem 3D para Jogos Digitais (Parte 1)',
       'Modelagem 3D para Jogos Digitais (Parte 2)',
       'Palestra: Introdução ao Tizen',
       'Criação de Jogos 3D com Unity (Parte 1)',
       'Criação de Jogos 3D com Unity (Parte 2)',
       'Introdução a UI e UX para Jogos Digitais',
       'Criação de interface para jogos com Unity',
       'Web Scraping com Python (Parte 1) ',
       'Laboratório de IoT em Cloud',
       'Web Scraping com Python (Parte 2)     ',
       'Otimizando jogos para celulares',
       'Impressão e escaneamento 3D: métodos subtrativos e aditivos (Parte 4)',
       'Desenvolvimento Ágil - DevOps Git',
       'Impressão e escaneamento 3D: métodos subtrativos e aditivos (Parte 1)',
       'Eletrônica para Fabricação Digital (Parte 1)',
       'Impressão e escaneamento 3D: métodos subtrativos e aditivos (Parte 2)',
       'Eletrônica para Fabricação Digital (Parte 2)',
       'Android: GPS com Google Maps', 'V1: Introdução ao XR',
       'Android: Webservices com Retrofit e Imagens com Glide',
       'Impressão e escaneamento 3D: métodos subtrativos e aditivos (Parte 3)',
       'Design Thinking: Conceitos e Prática',
       'Fundamentos da Indústria 4.0 - Módulo: Básico - (Parte 01)',
       'Eletrônica para Fabricação Digital (Parte 3)',
       'Fundamentos da Indústria 4.0 - Módulo: Básico - (Parte 02)',
       'Fundamentos da Indústria 4.0 – Módulo: Básico - (Parte 03)',
       'Eletrônica para Fabricação Digital (Parte 4)',
       'Android: Listas com RecyclerView e Multithread',
       'Android: Banco de Dados com Android Room',
       'Introdução à análise de dados geográficos com Python (Parte 1)',
       'Eletrônica para Fabricação Digital (Parte 5)',
       'Introdução à análise de dados geográficos com Python (Parte 2)',
       'Mindset Global',
       'V4: Realidade Aumentada: Laboratório com Unity e AR Foundation',
       'Android: Push Notification com Firebase',
       'IOT: Laboratório de IoT com Arduino',
       'Linguagem Python: aprendendo a linguagem (Aula prática)',
       'Tópicos de UX para Internet das Coisas',
       'Android: Jetpack e Arquitetura',
       'Assistente Virtual de Voz em Bixby - Trazendo Inteligência à Interface',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC (Parte 1)',
       'Ferramentas de desenvolvimento de dApps e Contratos inteligentes para Blockchain Ethereum',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC  (Parte 2)',
       'Desenvolvimento de dApps e Contratos inteligentes para Blockchain Ethereum',
       'Criação de Jogos 2D com Unity  (Parte 2)',
       'Criação de Jogos 2D com Unity',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC  (Parte 3)',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC (Parte 4)',
       'Introdução ao Deep Learning (Parte 1)',
       'Introdução ao Deep Learning (Parte 2)',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC (Parte 5)',
       'Tópicos de UX para VR e AR',
       'Introdução à análise de dados geográficos com Python (parte 1)',
       'Frontend Web com ReactJS: Introdução (Parte 3)',
       'Machine Learning: Entendendo e implementando com Orange',
       'Tópicos de UX para IA: Interfaces Conversacionais',
       'Desenvolvimento Ágil: Introdução',
       'Entendendo e implementando Machine Learning com Orange (Parte 1)',
       'Entendendo e implementando Machine Learning com Orange (Parte 2)',
       'Entendendo e implementando Machine Learning com Orange (Parte 3)',
       'Comunicação IoT utilizando ESP com interface visual do Processings (Parte 1)',
       '[IOT WEEK] WORKSHOP: Interface de Jogos para Telas Dobráveis',
       '[IOT WEEK] WORKSHOP: Entendendo e implementando Machine Learning',
       '[IOT WEEK] WORKSHOP: IoT em Nuvem com node-red',
       'Comunicação IoT utilizando ESP com interface visual do Processings (Parte 2)',
       'Backend com NodeJS e Express (Parte 2)',
       'Comunicação IoT utilizando ESP com interface visual do Processings (Parte 3)',
       'Android: Laborátorio', 'O que são Healthtechs?'], dtype=object)

In [16]:
#limpando os dados de título de curso 

#removendo espaços nos nomes do curso
new_values = df1["eve_title"].apply(lambda data: re.sub(r"\s","",data).lower())
df1["course_name"] = new_values

In [17]:
##criando a coluna de trilhas 
df1["eve_trilha"] = 0
df1.columns

Index(['eve_id', 'eve_title', 'eve_vacancy', 'eve_workload', 'eve_start_date',
       'eve_end_date', 'eve_start_hour', 'eve_end_hour',
       'eve_enrollment_start', 'eve_enrollment_end', 'eve_speaker_name',
       'eve_audience', 'eve_requirements', 'eve_creation_date',
       'fre_enr_stu_id', 'fre_cla_id', 'fre_status', 'stu_session', 'stu_name',
       'stu_cpf', 'stu_phone', 'stu_gender', 'stu_birth_date',
       'stu_creation_date', 'stu_last_login', 'stu_email', 'course_name',
       'eve_trilha'],
      dtype='object')

In [18]:
df1.course_name

0        tizen:ferramentaeambientededesenvolvimento
1        tizen:ferramentaeambientededesenvolvimento
2        tizen:ferramentaeambientededesenvolvimento
3        tizen:ferramentaeambientededesenvolvimento
4        tizen:ferramentaeambientededesenvolvimento
                            ...
88587                           android:laborátorio
88775                           oquesãohealthtechs?
88776                           oquesãohealthtechs?
88777                           oquesãohealthtechs?
88778                           oquesãohealthtechs?
Name: course_name, Length: 82930, dtype: object

In [19]:
#removendo cursos não interessantes 
excluded_courses = ["ux","email","indústria4.0","cidadesinteligentes","usabilidade","designthinking"]
for word in excluded_courses:
    excluded = search_word(df1,"course_name",word)
    df1.drop(excluded.index,axis=0,inplace=True)

In [20]:
df1.eve_title.unique()

array(['Tizen: Ferramenta e Ambiente de Desenvolvimento',
       'Introdução a Análise de Dados Geográficos com Python',
       'Tizen: Desenvolvimento de aplicação para ambiente Tizen',
       'Introdução à Internet das Coisas',
       'Laboratório de IoT com Arduino',
       'Programando para web com Python, CSS e HTML (Parte 1)',
       'Programando para web com Python, CSS e HTML (Parte 2)',
       'Desenvolvimento Ágil - DevOps Docker',
       'Desenvolvimento Ágil: DevOps GIT',
       'Introdução ao Backend com NodeJs e Express',
       'Laboratório de IoT com Raspberry Pi',
       'Laboratório de Backend com NodeJs e Express',
       'Linguagem Python: aprendendo a linguagem (Parte1)',
       'Linguagem Python: aprendendo a linguagem (Parte 2)',
       'Linguagem Python: aprendendo a linguagem (Parte 3)',
       'Introdução ao Frontend Web com React',
       'Introdução ao Deep Learning com Python e Keras (Parte 1)',
       'Introdução ao Deep Learning com Python e Keras (Parte 2)',
       'Palestra: Assistente Virtual de Voz em Bixby - Trazendo Inteligência à Interface',
       'Integrando os serviços de backend na nuvem',
       'Laboratório de Frontend Web com React',
       'Mineração de Opinião com Python', 'Android: Introdução',
       'Android: Laboratório', 'Web Scraping com Python (Parte 1)',
       'Web Scraping com Python (Parte 2)',
       'Web Scraping com Python (Parte 3)', 'Introdução ao Blockchain',
       'Ciência de Dados: Visualização de Dados com Python (Parte 1)',
       'Ciência de Dados: Visualização de Dados com Python (Parte 2)',
       'Jogos Digitais: Jogo 2D com Unity (Parte 1)',
       'Jogos Digitais: Jogo 2D com Unity (Parte 2)',
       'Introdução a Análise de Dados Geográficos com Python (Parte 1)',
       'Introdução a Análise de Dados Geográficos com Python (Parte 2)',
       'Introdução a Análise de Dados Geográficos com Python (Parte 3)',
       'Introdução aos dispositivos Wearables',
       'Oficina: Ferramentas de Suporte a Programação para Blockchain',
       'Ciência de Dados: Fundamentos de análise de dados com Orange',
       'Laboratório de Backend e Banco de Dados com MongoDB',
       'Backend com NodeJs e Express (Parte 1)',
       'Backend com NodeJs e Express (Parte 2)',
       'Oficina: Programação de uma aplicação para Blockchain',
       'Consultando Bases SQL com Python (Parte 1)',
       'Consultando Bases SQL com Python (Parte 2)',
       'Introdução ao Frontend Web com React (Parte 1)',
       'Introdução ao Frontend Web com React (Parte 2)',
       'Introdução a Internet das Coisas',
       '(Jornada Android) Android: Introdução',
       '(Jornada Android) Android: Laboratório',
       '(Jornada Android) Android: GPS com Google Maps',
       '(Jornada Android) Android: Webservices com Retrofit e Imagens com Glide',
       '(Jornada Android) Android: Listas com RecyclerView e Multithread',
       '(Jornada Android) Android: Banco de Dados com Android Room',
       '(Jornada Android) Android: Push Notification com Firebase',
       '(Jornada Android) Android: Jetpack e Arquitetura',
       'Ciência de Dados: Fundamentos de Análise de Dados com Orange',
       'Linguagem Python: aprendendo a linguagem (Parte 1)',
       'Jogos Digitais: Introdução',
       'Realidade Virtual, Aumentada e Mista: Introdução ao XR',
       'Frontend Web com ReactJS: Introdução (Parte 1)',
       'Frontend Web com ReactJS: Introdução (Parte 2)',
       'Palestra: Introdução ao Blockchain',
       'Desenvolvimento Ágil - DevOps GIT',
       'Frontend Web com ReactJS - Integração com Backend (Parte 1)',
       'Frontend Web com ReactJS - Integração com Backend (Parte 2)',
       'IOT: Laboratório de IOT com Arduino', 'Introdução à IoT',
       'IOT: Laboratório de IoT com Raspberry Pi',
       'IOT: Laboratório de IoT em Cloud',
       'Módulo 4: Avançando com Deep Learning',
       'Deep Learning: Introdução com Keras e Python (Parte 1)',
       'Oficina de Jogos 2D com Unity (Parte 1)',
       'Oficina de Jogos 2D com Unity (Parte 2)',
       'Oficina de Jogos 2D com Unity (Parte 3)',
       'Deep Learning: Introdução com Keras e Python (Parte 2)',
       'Oficina de Realidade Aumentada',
       'Jogos Digitais: Jogo 3D com Unity (Parte 1)',
       'Palestra: T1 - Introdução ao Tizen',
       'Programando para web com Python, CSS e HTML (Parte 3)',
       'Jogos Digitais: Jogo 3D com Unity (Parte 2)',
       ' Web Scraping com Python (Parte 1)',
       'Aprendendo a programar do zero (Parte 1)',
       'Aprendendo a programar do zero (Parte 2)',
       'Interface de jogos para telas dobráveis Games, AR and VR',
       'Introdução aos Jogos Digitais',
       'Criação de Jogos 2D com Unity (Parte 1)',
       'Palestra: Introdução ao Blockchain ',
       'Criação de Jogos 2D com Unity (Parte 2)',
       'Modelagem 3D para Jogos Digitais (Parte 1)',
       'Modelagem 3D para Jogos Digitais (Parte 2)',
       'Palestra: Introdução ao Tizen',
       'Criação de Jogos 3D com Unity (Parte 1)',
       'Criação de Jogos 3D com Unity (Parte 2)',
       'Criação de interface para jogos com Unity',
       'Web Scraping com Python (Parte 1) ',
       'Laboratório de IoT em Cloud',
       'Web Scraping com Python (Parte 2)     ',
       'Otimizando jogos para celulares',
       'Impressão e escaneamento 3D: métodos subtrativos e aditivos (Parte 4)',
       'Desenvolvimento Ágil - DevOps Git',
       'Impressão e escaneamento 3D: métodos subtrativos e aditivos (Parte 1)',
       'Eletrônica para Fabricação Digital (Parte 1)',
       'Impressão e escaneamento 3D: métodos subtrativos e aditivos (Parte 2)',
       'Eletrônica para Fabricação Digital (Parte 2)',
       'Android: GPS com Google Maps', 'V1: Introdução ao XR',
       'Android: Webservices com Retrofit e Imagens com Glide',
       'Impressão e escaneamento 3D: métodos subtrativos e aditivos (Parte 3)',
       'Eletrônica para Fabricação Digital (Parte 3)',
       'Eletrônica para Fabricação Digital (Parte 4)',
       'Android: Listas com RecyclerView e Multithread',
       'Android: Banco de Dados com Android Room',
       'Introdução à análise de dados geográficos com Python (Parte 1)',
       'Eletrônica para Fabricação Digital (Parte 5)',
       'Introdução à análise de dados geográficos com Python (Parte 2)',
       'Mindset Global',
       'V4: Realidade Aumentada: Laboratório com Unity e AR Foundation',
       'Android: Push Notification com Firebase',
       'IOT: Laboratório de IoT com Arduino',
       'Linguagem Python: aprendendo a linguagem (Aula prática)',
       'Android: Jetpack e Arquitetura',
       'Assistente Virtual de Voz em Bixby - Trazendo Inteligência à Interface',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC (Parte 1)',
       'Ferramentas de desenvolvimento de dApps e Contratos inteligentes para Blockchain Ethereum',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC  (Parte 2)',
       'Desenvolvimento de dApps e Contratos inteligentes para Blockchain Ethereum',
       'Criação de Jogos 2D com Unity  (Parte 2)',
       'Criação de Jogos 2D com Unity',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC  (Parte 3)',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC (Parte 4)',
       'Introdução ao Deep Learning (Parte 1)',
       'Introdução ao Deep Learning (Parte 2)',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC (Parte 5)',
       'Introdução à análise de dados geográficos com Python (parte 1)',
       'Frontend Web com ReactJS: Introdução (Parte 3)',
       'Machine Learning: Entendendo e implementando com Orange',
       'Desenvolvimento Ágil: Introdução',
       'Entendendo e implementando Machine Learning com Orange (Parte 1)',
       'Entendendo e implementando Machine Learning com Orange (Parte 2)',
       'Entendendo e implementando Machine Learning com Orange (Parte 3)',
       'Comunicação IoT utilizando ESP com interface visual do Processings (Parte 1)',
       '[IOT WEEK] WORKSHOP: Interface de Jogos para Telas Dobráveis',
       '[IOT WEEK] WORKSHOP: Entendendo e implementando Machine Learning',
       '[IOT WEEK] WORKSHOP: IoT em Nuvem com node-red',
       'Comunicação IoT utilizando ESP com interface visual do Processings (Parte 2)',
       'Backend com NodeJS e Express (Parte 2)',
       'Comunicação IoT utilizando ESP com interface visual do Processings (Parte 3)',
       'Android: Laborátorio', 'O que são Healthtechs?'], dtype=object)

In [21]:
#excluding more irrevalant courses
more_excluded_courses = ["HealthTechs","Mindset"]
for word in more_excluded_courses:
    excluded = search_word(df1,"course_name",word)
    df1.drop(excluded.index,axis=0,inplace=True)

In [22]:
df1.eve_title.unique()

array(['Tizen: Ferramenta e Ambiente de Desenvolvimento',
       'Introdução a Análise de Dados Geográficos com Python',
       'Tizen: Desenvolvimento de aplicação para ambiente Tizen',
       'Introdução à Internet das Coisas',
       'Laboratório de IoT com Arduino',
       'Programando para web com Python, CSS e HTML (Parte 1)',
       'Programando para web com Python, CSS e HTML (Parte 2)',
       'Desenvolvimento Ágil - DevOps Docker',
       'Desenvolvimento Ágil: DevOps GIT',
       'Introdução ao Backend com NodeJs e Express',
       'Laboratório de IoT com Raspberry Pi',
       'Laboratório de Backend com NodeJs e Express',
       'Linguagem Python: aprendendo a linguagem (Parte1)',
       'Linguagem Python: aprendendo a linguagem (Parte 2)',
       'Linguagem Python: aprendendo a linguagem (Parte 3)',
       'Introdução ao Frontend Web com React',
       'Introdução ao Deep Learning com Python e Keras (Parte 1)',
       'Introdução ao Deep Learning com Python e Keras (Parte 2)',
       'Palestra: Assistente Virtual de Voz em Bixby - Trazendo Inteligência à Interface',
       'Integrando os serviços de backend na nuvem',
       'Laboratório de Frontend Web com React',
       'Mineração de Opinião com Python', 'Android: Introdução',
       'Android: Laboratório', 'Web Scraping com Python (Parte 1)',
       'Web Scraping com Python (Parte 2)',
       'Web Scraping com Python (Parte 3)', 'Introdução ao Blockchain',
       'Ciência de Dados: Visualização de Dados com Python (Parte 1)',
       'Ciência de Dados: Visualização de Dados com Python (Parte 2)',
       'Jogos Digitais: Jogo 2D com Unity (Parte 1)',
       'Jogos Digitais: Jogo 2D com Unity (Parte 2)',
       'Introdução a Análise de Dados Geográficos com Python (Parte 1)',
       'Introdução a Análise de Dados Geográficos com Python (Parte 2)',
       'Introdução a Análise de Dados Geográficos com Python (Parte 3)',
       'Introdução aos dispositivos Wearables',
       'Oficina: Ferramentas de Suporte a Programação para Blockchain',
       'Ciência de Dados: Fundamentos de análise de dados com Orange',
       'Laboratório de Backend e Banco de Dados com MongoDB',
       'Backend com NodeJs e Express (Parte 1)',
       'Backend com NodeJs e Express (Parte 2)',
       'Oficina: Programação de uma aplicação para Blockchain',
       'Consultando Bases SQL com Python (Parte 1)',
       'Consultando Bases SQL com Python (Parte 2)',
       'Introdução ao Frontend Web com React (Parte 1)',
       'Introdução ao Frontend Web com React (Parte 2)',
       'Introdução a Internet das Coisas',
       '(Jornada Android) Android: Introdução',
       '(Jornada Android) Android: Laboratório',
       '(Jornada Android) Android: GPS com Google Maps',
       '(Jornada Android) Android: Webservices com Retrofit e Imagens com Glide',
       '(Jornada Android) Android: Listas com RecyclerView e Multithread',
       '(Jornada Android) Android: Banco de Dados com Android Room',
       '(Jornada Android) Android: Push Notification com Firebase',
       '(Jornada Android) Android: Jetpack e Arquitetura',
       'Ciência de Dados: Fundamentos de Análise de Dados com Orange',
       'Linguagem Python: aprendendo a linguagem (Parte 1)',
       'Jogos Digitais: Introdução',
       'Realidade Virtual, Aumentada e Mista: Introdução ao XR',
       'Frontend Web com ReactJS: Introdução (Parte 1)',
       'Frontend Web com ReactJS: Introdução (Parte 2)',
       'Palestra: Introdução ao Blockchain',
       'Desenvolvimento Ágil - DevOps GIT',
       'Frontend Web com ReactJS - Integração com Backend (Parte 1)',
       'Frontend Web com ReactJS - Integração com Backend (Parte 2)',
       'IOT: Laboratório de IOT com Arduino', 'Introdução à IoT',
       'IOT: Laboratório de IoT com Raspberry Pi',
       'IOT: Laboratório de IoT em Cloud',
       'Módulo 4: Avançando com Deep Learning',
       'Deep Learning: Introdução com Keras e Python (Parte 1)',
       'Oficina de Jogos 2D com Unity (Parte 1)',
       'Oficina de Jogos 2D com Unity (Parte 2)',
       'Oficina de Jogos 2D com Unity (Parte 3)',
       'Deep Learning: Introdução com Keras e Python (Parte 2)',
       'Oficina de Realidade Aumentada',
       'Jogos Digitais: Jogo 3D com Unity (Parte 1)',
       'Palestra: T1 - Introdução ao Tizen',
       'Programando para web com Python, CSS e HTML (Parte 3)',
       'Jogos Digitais: Jogo 3D com Unity (Parte 2)',
       ' Web Scraping com Python (Parte 1)',
       'Aprendendo a programar do zero (Parte 1)',
       'Aprendendo a programar do zero (Parte 2)',
       'Interface de jogos para telas dobráveis Games, AR and VR',
       'Introdução aos Jogos Digitais',
       'Criação de Jogos 2D com Unity (Parte 1)',
       'Palestra: Introdução ao Blockchain ',
       'Criação de Jogos 2D com Unity (Parte 2)',
       'Modelagem 3D para Jogos Digitais (Parte 1)',
       'Modelagem 3D para Jogos Digitais (Parte 2)',
       'Palestra: Introdução ao Tizen',
       'Criação de Jogos 3D com Unity (Parte 1)',
       'Criação de Jogos 3D com Unity (Parte 2)',
       'Criação de interface para jogos com Unity',
       'Web Scraping com Python (Parte 1) ',
       'Laboratório de IoT em Cloud',
       'Web Scraping com Python (Parte 2)     ',
       'Otimizando jogos para celulares',
       'Impressão e escaneamento 3D: métodos subtrativos e aditivos (Parte 4)',
       'Desenvolvimento Ágil - DevOps Git',
       'Impressão e escaneamento 3D: métodos subtrativos e aditivos (Parte 1)',
       'Eletrônica para Fabricação Digital (Parte 1)',
       'Impressão e escaneamento 3D: métodos subtrativos e aditivos (Parte 2)',
       'Eletrônica para Fabricação Digital (Parte 2)',
       'Android: GPS com Google Maps', 'V1: Introdução ao XR',
       'Android: Webservices com Retrofit e Imagens com Glide',
       'Impressão e escaneamento 3D: métodos subtrativos e aditivos (Parte 3)',
       'Eletrônica para Fabricação Digital (Parte 3)',
       'Eletrônica para Fabricação Digital (Parte 4)',
       'Android: Listas com RecyclerView e Multithread',
       'Android: Banco de Dados com Android Room',
       'Introdução à análise de dados geográficos com Python (Parte 1)',
       'Eletrônica para Fabricação Digital (Parte 5)',
       'Introdução à análise de dados geográficos com Python (Parte 2)',
       'V4: Realidade Aumentada: Laboratório com Unity e AR Foundation',
       'Android: Push Notification com Firebase',
       'IOT: Laboratório de IoT com Arduino',
       'Linguagem Python: aprendendo a linguagem (Aula prática)',
       'Android: Jetpack e Arquitetura',
       'Assistente Virtual de Voz em Bixby - Trazendo Inteligência à Interface',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC (Parte 1)',
       'Ferramentas de desenvolvimento de dApps e Contratos inteligentes para Blockchain Ethereum',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC  (Parte 2)',
       'Desenvolvimento de dApps e Contratos inteligentes para Blockchain Ethereum',
       'Criação de Jogos 2D com Unity  (Parte 2)',
       'Criação de Jogos 2D com Unity',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC  (Parte 3)',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC (Parte 4)',
       'Introdução ao Deep Learning (Parte 1)',
       'Introdução ao Deep Learning (Parte 2)',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC (Parte 5)',
       'Introdução à análise de dados geográficos com Python (parte 1)',
       'Frontend Web com ReactJS: Introdução (Parte 3)',
       'Machine Learning: Entendendo e implementando com Orange',
       'Desenvolvimento Ágil: Introdução',
       'Entendendo e implementando Machine Learning com Orange (Parte 1)',
       'Entendendo e implementando Machine Learning com Orange (Parte 2)',
       'Entendendo e implementando Machine Learning com Orange (Parte 3)',
       'Comunicação IoT utilizando ESP com interface visual do Processings (Parte 1)',
       '[IOT WEEK] WORKSHOP: Interface de Jogos para Telas Dobráveis',
       '[IOT WEEK] WORKSHOP: Entendendo e implementando Machine Learning',
       '[IOT WEEK] WORKSHOP: IoT em Nuvem com node-red',
       'Comunicação IoT utilizando ESP com interface visual do Processings (Parte 2)',
       'Backend com NodeJS e Express (Parte 2)',
       'Comunicação IoT utilizando ESP com interface visual do Processings (Parte 3)',
       'Android: Laborátorio'], dtype=object)

In [65]:
#definindo as trilhas
trilhas = {"IAR":"IAR","BXB":"BXB","IOT":"IOT","TZN":"TZN","BLC":"BLC",
           "GME":"GME","LAB":"LAB","NGC":"NGC","RVA":"RVA","TALK":"TALK",
           "PRG":"PRG","AND":"AND","ÁGIL":"ÁGIL","INT":"INT","FRTEND":"FRTEND","WRB":"WRB","BCKEND":"BCKEND","FABLAB":"FABLAB"}

In [24]:
def set_trilha(df,df_search,trilha):
    df_search.loc[:,"eve_trilha"]= trilha
    df.loc[df_search.index,"eve_trilha"]=trilha
    return df

In [25]:
#função para definir sessões 
def define_session(data):
    session = re.findall(r"\d",data)
    if len(session)>0:
        return session[0]
    else:
        return "-"

In [26]:
#criando a coluna is_session para definir os cursos com mais de uma sessão
df1["is_session"] = 0
new_values = df1["eve_title"].apply(lambda data: define_session(data))
df1["is_session"] = new_values

In [27]:
df1[:11]

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
0,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,22657434886,11985466144,M,1984-07-31,2021-11-05 17:11:25,2019-05-28 20:39:38,orleansklaus@gmail.com,tizen:ferramentaeambientededesenvolvimento,0,-
1,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,38533792816,11984061040,M,1991-08-26,2021-10-01 01:31:45,NaN,aguiar.rafaelm@gmail.com,tizen:ferramentaeambientededesenvolvimento,0,-
2,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,89609034268,92991015108,M,1986-05-16,2021-05-14 00:14:44,NaN,anglops@gmail.com,tizen:ferramentaeambientededesenvolvimento,0,-
3,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,00289630240,92991551517,M,1989-11-09,2021-08-17 23:45:03,NaN,gerson.cunha@outlook.com,tizen:ferramentaeambientededesenvolvimento,0,-
4,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,01603746269,92984041284,M,1997-08-21,2021-05-10 20:30:46,2019-02-20 08:02:28,gqs.snf17@uea.edu.br,tizen:ferramentaeambientededesenvolvimento,0,-
5,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,01635111285,92992789002,M,1994-03-28,2021-08-26 19:13:38,NaN,rafael_dk14@hotmail.com,tizen:ferramentaeambientededesenvolvimento,0,-
6,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,94010390204,NaN,M,1988-10-07,2018-02-21 20:18:40,NaN,vargas.reynaldo22@gmail.com,tizen:ferramentaeambientededesenvolvimento,0,-
7,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,00959273280,92993929290,F,1991-01-19,2021-11-05 17:11:25,NaN,samia_lyma@hotmail.com,tizen:ferramentaeambientededesenvolvimento,0,-
8,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,30915747847,11999999999,M,1982-10-07,2021-11-11 00:19:05,2019-05-17 01:24:05,rob.constante@gmail.com,tizen:ferramentaeambientededesenvolvimento,0,-
9,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,74968998287,92991056224,F,1984-01-05,2021-10-01 01:12:59,2019-07-24 14:20:34,elizabeth@cide.org.br,tizen:ferramentaeambientededesenvolvimento,0,-
10,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,02806338239,92981226526,F,1994-06-30,2021-05-10 20:30:46,2019-03-15 22:20:47,tammyhikari@gmail.com,tizen:ferramentaeambientededesenvolvimento,0,-

Trilha dos cursos

trilha android

In [28]:
df_android = search_word(df1,"course_name","android")
df_android

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
5369,2328,Android: Introdução,600,03:00,2021-05-18,2021-05-18,10:00,13:00,2021-04-26,2021-05-18,...,88370992234,92981538181,M,1986-03-08,2021-06-01 22:48:27,2018-05-02 19:27:55,filhomarlon@hotmail.com,android:introdução,0,-
5370,2328,Android: Introdução,600,03:00,2021-05-18,2021-05-18,10:00,13:00,2021-04-26,2021-05-18,...,22657434886,11985466144,M,1984-07-31,2021-11-05 17:11:25,2019-05-28 20:39:38,orleansklaus@gmail.com,android:introdução,0,-
5371,2328,Android: Introdução,600,03:00,2021-05-18,2021-05-18,10:00,13:00,2021-04-26,2021-05-18,...,38533792816,11984061040,M,1991-08-26,2021-10-01 01:31:45,NaN,aguiar.rafaelm@gmail.com,android:introdução,0,-
5372,2328,Android: Introdução,600,03:00,2021-05-18,2021-05-18,10:00,13:00,2021-04-26,2021-05-18,...,00759195242,92992421922,F,1991-11-01,2021-11-23 14:59:13,2018-03-17 15:44:28,jessicab.melo9@gmail.com,android:introdução,0,-
5373,2328,Android: Introdução,600,03:00,2021-05-18,2021-05-18,10:00,13:00,2021-04-26,2021-05-18,...,30439218870,11952254653,M,2016-08-10,2021-11-11 00:22:42,2019-06-15 18:00:21,pregadorkg@gmail.com,android:introdução,0,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88583,2770,Android: Laborátorio,600,03:00,2021-12-13,2021-12-13,14:00,17:00,1970-01-01,1970-01-01,...,70326324240,92991598464,F,2000-09-14,2021-12-14 03:23:44,2021-12-10 16:54:18,remacielsantos@gmail.com,android:laborátorio,0,-
88584,2770,Android: Laborátorio,600,03:00,2021-12-13,2021-12-13,14:00,17:00,1970-01-01,1970-01-01,...,5419082276,97984029973,M,1998-05-21,2021-12-14 03:23:44,2021-12-10 18:25:53,matheusmc210598@gmail.com,android:laborátorio,0,-
88585,2770,Android: Laborátorio,600,03:00,2021-12-13,2021-12-13,14:00,17:00,1970-01-01,1970-01-01,...,1633608204,92999026351,M,1998-08-03,2021-12-20 15:30:53,2021-12-10 20:41:28,jeancarlosfr91@gmail.com,android:laborátorio,0,-
88586,2770,Android: Laborátorio,600,03:00,2021-12-13,2021-12-13,14:00,17:00,1970-01-01,1970-01-01,...,70135747244,92992396519,M,2003-01-28,2021-12-15 11:29:26,2021-12-13 01:21:26,gabriel992396519@gmail.com,android:laborátorio,0,-
88587,2770,Android: Laborátorio,600,03:00,2021-12-13,2021-12-13,14:00,17:00,1970-01-01,1970-01-01,...,70461318210,92994103055,F,2002-03-13,2021-12-20 15:30:56,2021-12-13 01:33:21,mikaellemayres7@gmail.com,android:laborátorio,0,-

In [29]:
#definindo a trilha android 
df1 = set_trilha(df1,df_android,trilhas["AND"])
df1.head()

c:\Users\Talissa\Documents\env\ocean_bi_env\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
0,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,22657434886,11985466144,M,1984-07-31,2021-11-05 17:11:25,2019-05-28 20:39:38,orleansklaus@gmail.com,tizen:ferramentaeambientededesenvolvimento,0,-
1,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,38533792816,11984061040,M,1991-08-26,2021-10-01 01:31:45,NaN,aguiar.rafaelm@gmail.com,tizen:ferramentaeambientededesenvolvimento,0,-
2,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,89609034268,92991015108,M,1986-05-16,2021-05-14 00:14:44,NaN,anglops@gmail.com,tizen:ferramentaeambientededesenvolvimento,0,-
3,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,00289630240,92991551517,M,1989-11-09,2021-08-17 23:45:03,NaN,gerson.cunha@outlook.com,tizen:ferramentaeambientededesenvolvimento,0,-
4,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,01603746269,92984041284,M,1997-08-21,2021-05-10 20:30:46,2019-02-20 08:02:28,gqs.snf17@uea.edu.br,tizen:ferramentaeambientededesenvolvimento,0,-

trilha tizen

In [30]:
df_tizen = search_word(df1,"course_name","tizen")
df_tizen.head()

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
0,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,22657434886,11985466144,M,1984-07-31,2021-11-05 17:11:25,2019-05-28 20:39:38,orleansklaus@gmail.com,tizen:ferramentaeambientededesenvolvimento,0,-
1,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,38533792816,11984061040,M,1991-08-26,2021-10-01 01:31:45,NaN,aguiar.rafaelm@gmail.com,tizen:ferramentaeambientededesenvolvimento,0,-
2,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,89609034268,92991015108,M,1986-05-16,2021-05-14 00:14:44,NaN,anglops@gmail.com,tizen:ferramentaeambientededesenvolvimento,0,-
3,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,00289630240,92991551517,M,1989-11-09,2021-08-17 23:45:03,NaN,gerson.cunha@outlook.com,tizen:ferramentaeambientededesenvolvimento,0,-
4,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,01603746269,92984041284,M,1997-08-21,2021-05-10 20:30:46,2019-02-20 08:02:28,gqs.snf17@uea.edu.br,tizen:ferramentaeambientededesenvolvimento,0,-

In [31]:
df1 = set_trilha(df1,df_tizen,trilhas["TZN"])
df1.head()

c:\Users\Talissa\Documents\env\ocean_bi_env\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
0,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,22657434886,11985466144,M,1984-07-31,2021-11-05 17:11:25,2019-05-28 20:39:38,orleansklaus@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
1,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,38533792816,11984061040,M,1991-08-26,2021-10-01 01:31:45,NaN,aguiar.rafaelm@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
2,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,89609034268,92991015108,M,1986-05-16,2021-05-14 00:14:44,NaN,anglops@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
3,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,00289630240,92991551517,M,1989-11-09,2021-08-17 23:45:03,NaN,gerson.cunha@outlook.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
4,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,01603746269,92984041284,M,1997-08-21,2021-05-10 20:30:46,2019-02-20 08:02:28,gqs.snf17@uea.edu.br,tizen:ferramentaeambientededesenvolvimento,TZN,-

trilha jogos

In [62]:
df_jogos = search_word(df1,"course_name","jogos|realidade|XR")
df_jogos

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
7626,2337,Jogos Digitais: Jogo 2D com Unity (Parte 1),300,03:00,2021-05-25,2021-05-25,10:00,13:00,2021-04-26,2021-05-25,...,22657434886,11985466144,M,1984-07-31,2021-11-05 17:11:25,2019-05-28 20:39:38,orleansklaus@gmail.com,jogosdigitais:jogo2dcomunity(parte1),ÁGIL,2
7627,2337,Jogos Digitais: Jogo 2D com Unity (Parte 1),300,03:00,2021-05-25,2021-05-25,10:00,13:00,2021-04-26,2021-05-25,...,38533792816,11984061040,M,1991-08-26,2021-10-01 01:31:45,NaN,aguiar.rafaelm@gmail.com,jogosdigitais:jogo2dcomunity(parte1),ÁGIL,2
7628,2337,Jogos Digitais: Jogo 2D com Unity (Parte 1),300,03:00,2021-05-25,2021-05-25,10:00,13:00,2021-04-26,2021-05-25,...,98556851215,92981478948,M,1988-02-24,2021-08-31 02:14:20,NaN,moises.de.menezes@gmail.com,jogosdigitais:jogo2dcomunity(parte1),ÁGIL,2
7629,2337,Jogos Digitais: Jogo 2D com Unity (Parte 1),300,03:00,2021-05-25,2021-05-25,10:00,13:00,2021-04-26,2021-05-25,...,83659706272,92984109420,F,1986-08-27,2021-10-22 20:16:09,NaN,barroskatleen@gmail.com,jogosdigitais:jogo2dcomunity(parte1),ÁGIL,2
7630,2337,Jogos Digitais: Jogo 2D com Unity (Parte 1),300,03:00,2021-05-25,2021-05-25,10:00,13:00,2021-04-26,2021-05-25,...,00289630240,92991551517,M,1989-11-09,2021-08-17 23:45:03,NaN,gerson.cunha@outlook.com,jogosdigitais:jogo2dcomunity(parte1),ÁGIL,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87173,2755,[IOT WEEK] WORKSHOP: Interface de Jogos para T...,200,03:00,2021-12-14,2021-12-14,14:00,17:15,2021-11-24,2021-12-14,...,1633608204,92999026351,M,1998-08-03,2021-12-20 15:30:53,2021-12-10 20:41:28,jeancarlosfr91@gmail.com,[iotweek]workshop:interfacedejogosparatelasdob...,IOT,-
87174,2755,[IOT WEEK] WORKSHOP: Interface de Jogos para T...,200,03:00,2021-12-14,2021-12-14,14:00,17:15,2021-11-24,2021-12-14,...,70135747244,92992396519,M,2003-01-28,2021-12-15 11:29:26,2021-12-13 01:21:26,gabriel992396519@gmail.com,[iotweek]workshop:interfacedejogosparatelasdob...,IOT,-
87175,2755,[IOT WEEK] WORKSHOP: Interface de Jogos para T...,200,03:00,2021-12-14,2021-12-14,14:00,17:15,2021-11-24,2021-12-14,...,70461318210,92994103055,F,2002-03-13,2021-12-20 15:30:56,2021-12-13 01:33:21,mikaellemayres7@gmail.com,[iotweek]workshop:interfacedejogosparatelasdob...,IOT,-
87176,2755,[IOT WEEK] WORKSHOP: Interface de Jogos para T...,200,03:00,2021-12-14,2021-12-14,14:00,17:15,2021-11-24,2021-12-14,...,99452391200,92984190091,M,2000-04-06,2021-12-15 11:36:47,2021-12-14 12:25:20,thiagorm5465@gmail.com,[iotweek]workshop:interfacedejogosparatelasdob...,IOT,-
87177,2755,[IOT WEEK] WORKSHOP: Interface de Jogos para T...,200,03:00,2021-12-14,2021-12-14,14:00,17:15,2021-11-24,2021-12-14,...,5599155277,92986199312,F,2002-01-09,2021-12-15 11:29:28,2021-12-14 14:09:34,rebecaroque4321@gmail.com,[iotweek]workshop:interfacedejogosparatelasdob...,IOT,-

In [63]:
df1 = set_trilha(df1,df_jogos,trilhas["GME"])
df1.head()

c:\Users\Talissa\Documents\env\ocean_bi_env\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
0,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,22657434886,11985466144,M,1984-07-31,2021-11-05 17:11:25,2019-05-28 20:39:38,orleansklaus@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
1,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,38533792816,11984061040,M,1991-08-26,2021-10-01 01:31:45,NaN,aguiar.rafaelm@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
2,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,89609034268,92991015108,M,1986-05-16,2021-05-14 00:14:44,NaN,anglops@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
3,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,00289630240,92991551517,M,1989-11-09,2021-08-17 23:45:03,NaN,gerson.cunha@outlook.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
4,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,01603746269,92984041284,M,1997-08-21,2021-05-10 20:30:46,2019-02-20 08:02:28,gqs.snf17@uea.edu.br,tizen:ferramentaeambientededesenvolvimento,TZN,-

In [34]:
df_prgm = search_word(df1,"course_name","html|linguagempython|sql|programar")
df_prgm[:5]

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
1180,2304,"Programando para web com Python, CSS e HTML (P...",500,03:00,2021-04-28,2021-04-28,09:00,12:00,2021-04-09,2021-04-28,...,00556792262,92984022331,M,1992-03-02,2021-04-30 01:09:52,NaN,design.paortiz@gmail.com,"programandoparawebcompython,cssehtml(parte1)",0,1
1181,2304,"Programando para web com Python, CSS e HTML (P...",500,03:00,2021-04-28,2021-04-28,09:00,12:00,2021-04-09,2021-04-28,...,22657434886,11985466144,M,1984-07-31,2021-11-05 17:11:25,2019-05-28 20:39:38,orleansklaus@gmail.com,"programandoparawebcompython,cssehtml(parte1)",0,1
1182,2304,"Programando para web com Python, CSS e HTML (P...",500,03:00,2021-04-28,2021-04-28,09:00,12:00,2021-04-09,2021-04-28,...,02812621281,92995282706,M,1996-02-06,2021-07-30 05:12:59,NaN,alessy_padilha@hotmail.com,"programandoparawebcompython,cssehtml(parte1)",0,1
1183,2304,"Programando para web com Python, CSS e HTML (P...",500,03:00,2021-04-28,2021-04-28,09:00,12:00,2021-04-09,2021-04-28,...,38533792816,11984061040,M,1991-08-26,2021-10-01 01:31:45,NaN,aguiar.rafaelm@gmail.com,"programandoparawebcompython,cssehtml(parte1)",0,1
1184,2304,"Programando para web com Python, CSS e HTML (P...",500,03:00,2021-04-28,2021-04-28,09:00,12:00,2021-04-09,2021-04-28,...,89609034268,92991015108,M,1986-05-16,2021-05-14 00:14:44,NaN,anglops@gmail.com,"programandoparawebcompython,cssehtml(parte1)",0,1

In [35]:
df1 = set_trilha(df1,df_prgm,trilhas["PRG"])
df1.head()

c:\Users\Talissa\Documents\env\ocean_bi_env\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
0,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,22657434886,11985466144,M,1984-07-31,2021-11-05 17:11:25,2019-05-28 20:39:38,orleansklaus@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
1,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,38533792816,11984061040,M,1991-08-26,2021-10-01 01:31:45,NaN,aguiar.rafaelm@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
2,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,89609034268,92991015108,M,1986-05-16,2021-05-14 00:14:44,NaN,anglops@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
3,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,00289630240,92991551517,M,1989-11-09,2021-08-17 23:45:03,NaN,gerson.cunha@outlook.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
4,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,01603746269,92984041284,M,1997-08-21,2021-05-10 20:30:46,2019-02-20 08:02:28,gqs.snf17@uea.edu.br,tizen:ferramentaeambientededesenvolvimento,TZN,-

Trilha internet das coisas

In [36]:
df_iot = search_word(df1,"course_name","iot|internetdascoisas")
df_iot.shape

(5595, 29)

In [37]:
df1 = set_trilha(df1,df_iot,trilhas["IOT"])
df1.head()

c:\Users\Talissa\Documents\env\ocean_bi_env\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
0,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,22657434886,11985466144,M,1984-07-31,2021-11-05 17:11:25,2019-05-28 20:39:38,orleansklaus@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
1,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,38533792816,11984061040,M,1991-08-26,2021-10-01 01:31:45,NaN,aguiar.rafaelm@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
2,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,89609034268,92991015108,M,1986-05-16,2021-05-14 00:14:44,NaN,anglops@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
3,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,00289630240,92991551517,M,1989-11-09,2021-08-17 23:45:03,NaN,gerson.cunha@outlook.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
4,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,01603746269,92984041284,M,1997-08-21,2021-05-10 20:30:46,2019-02-20 08:02:28,gqs.snf17@uea.edu.br,tizen:ferramentaeambientededesenvolvimento,TZN,-

Trilha de frontend

In [38]:
df_ftend = search_word(df1,"course_name","frontend")
df_ftend.shape

(5428, 29)

In [39]:
df1 = set_trilha(df1,df_ftend,trilhas["FRTEND"])
df1.head()

c:\Users\Talissa\Documents\env\ocean_bi_env\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
0,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,22657434886,11985466144,M,1984-07-31,2021-11-05 17:11:25,2019-05-28 20:39:38,orleansklaus@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
1,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,38533792816,11984061040,M,1991-08-26,2021-10-01 01:31:45,NaN,aguiar.rafaelm@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
2,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,89609034268,92991015108,M,1986-05-16,2021-05-14 00:14:44,NaN,anglops@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
3,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,00289630240,92991551517,M,1989-11-09,2021-08-17 23:45:03,NaN,gerson.cunha@outlook.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
4,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,01603746269,92984041284,M,1997-08-21,2021-05-10 20:30:46,2019-02-20 08:02:28,gqs.snf17@uea.edu.br,tizen:ferramentaeambientededesenvolvimento,TZN,-

trilha de backend

In [40]:
df_bckend = search_word(df1,"course_name","backend")
df_bckend.shape

(6924, 29)

In [41]:
df1 = set_trilha(df1,df_bckend,trilhas["BCKEND"])
df1.head()

c:\Users\Talissa\Documents\env\ocean_bi_env\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
0,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,22657434886,11985466144,M,1984-07-31,2021-11-05 17:11:25,2019-05-28 20:39:38,orleansklaus@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
1,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,38533792816,11984061040,M,1991-08-26,2021-10-01 01:31:45,NaN,aguiar.rafaelm@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
2,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,89609034268,92991015108,M,1986-05-16,2021-05-14 00:14:44,NaN,anglops@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
3,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,00289630240,92991551517,M,1989-11-09,2021-08-17 23:45:03,NaN,gerson.cunha@outlook.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
4,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,2021-04-23,...,01603746269,92984041284,M,1997-08-21,2021-05-10 20:30:46,2019-02-20 08:02:28,gqs.snf17@uea.edu.br,tizen:ferramentaeambientededesenvolvimento,TZN,-

trilha Bixby

In [42]:
df_bxb = search_word(df1,"course_name","bixby")
df_bxb.shape

(709, 29)

In [43]:
df1 = set_trilha(df1,df_bxb,trilhas["BXB"])
df1.shape

c:\Users\Talissa\Documents\env\ocean_bi_env\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

(73412, 29)

trilha de Wearables

In [44]:
df_wrb = search_word(df1,"course_name","wearables")
df_wrb.shape

(442, 29)

In [45]:
df1 = set_trilha(df1,df_wrb,trilhas["WRB"])
df1.shape

(73412, 29)

trilha de blockchain

In [46]:
df_bcn = search_word(df1,"course_name","blockchain")
df_bcn.shape

(2834, 29)

In [47]:
df1 = set_trilha(df1,df_bcn,trilhas["BLC"])
df1.shape

(73412, 29)

trilha Ágil

In [59]:
df_agile = search_word(df1,"course_name","docker|git|ágil")
df_agile.shape

(4930, 29)

In [60]:
df1 = set_trilha(df1,df_agile,trilhas["ÁGIL"])
df1.shape

(73412, 29)

Trilha de ML

In [50]:
df_ml_outros = search_word(df1,"course_name","mineração|dadosgeográficos|webscraping")
df_ml_outros.shape

(7049, 29)

In [51]:
df1 = set_trilha(df1,df_ml_outros,trilhas["IAR"])
df1.shape

(73412, 29)

In [52]:
df_ml_dl = search_word(df1,"course_name","deeplearning")
df_ml_dl

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
3951,2320,Introdução ao Deep Learning com Python e Keras...,300,03:00,2021-05-10,2021-05-10,15:00,18:00,2021-04-26,2021-05-10,...,88370992234,92981538181,M,1986-03-08,2021-06-01 22:48:27,2018-05-02 19:27:55,filhomarlon@hotmail.com,introduçãoaodeeplearningcompythonekeras(parte1),0,1
3952,2320,Introdução ao Deep Learning com Python e Keras...,300,03:00,2021-05-10,2021-05-10,15:00,18:00,2021-04-26,2021-05-10,...,22657434886,11985466144,M,1984-07-31,2021-11-05 17:11:25,2019-05-28 20:39:38,orleansklaus@gmail.com,introduçãoaodeeplearningcompythonekeras(parte1),0,1
3953,2320,Introdução ao Deep Learning com Python e Keras...,300,03:00,2021-05-10,2021-05-10,15:00,18:00,2021-04-26,2021-05-10,...,63302764200,92991209232,M,2017-01-17,2021-05-28 00:25:20,NaN,ale_sbezerra@yahoo.com.br,introduçãoaodeeplearningcompythonekeras(parte1),0,1
3954,2320,Introdução ao Deep Learning com Python e Keras...,300,03:00,2021-05-10,2021-05-10,15:00,18:00,2021-04-26,2021-05-10,...,60311754287,9282041307,F,1977-09-17,2021-12-01 14:28:44,2019-07-05 14:49:22,nilmarasalgado@gmail.com,introduçãoaodeeplearningcompythonekeras(parte1),0,1
3955,2320,Introdução ao Deep Learning com Python e Keras...,300,03:00,2021-05-10,2021-05-10,15:00,18:00,2021-04-26,2021-05-10,...,72188065204,92981468411,F,1981-10-21,2021-12-20 15:39:02,2019-07-29 12:57:42,charlenesq.yah@gmail.com,introduçãoaodeeplearningcompythonekeras(parte1),0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79368,2679,Introdução ao Deep Learning (Parte 2),600,03:00,2021-11-17,2021-11-17,19:00,22:00,1970-01-01,1970-01-01,...,28332075149,61981575525,M,1964-03-01,2022-01-18 00:17:33,2021-11-13 13:39:28,marcos.antonio.carvalho@gmail.com,introduçãoaodeeplearning(parte2),0,2
79369,2679,Introdução ao Deep Learning (Parte 2),600,03:00,2021-11-17,2021-11-17,19:00,22:00,1970-01-01,1970-01-01,...,52231750856,11946680243,M,2004-08-18,2021-11-18 21:51:41,2021-11-15 20:07:28,falaiper.gomes@gmail.com,introduçãoaodeeplearning(parte2),0,2
79370,2679,Introdução ao Deep Learning (Parte 2),600,03:00,2021-11-17,2021-11-17,19:00,22:00,1970-01-01,1970-01-01,...,14776591707,21997762816,M,1992-11-08,2021-12-01 14:29:04,2021-11-16 01:16:39,pedroluisparavato@hotmail.com,introduçãoaodeeplearning(parte2),0,2
79371,2679,Introdução ao Deep Learning (Parte 2),600,03:00,2021-11-17,2021-11-17,19:00,22:00,1970-01-01,1970-01-01,...,36961121861,11999675927,M,1986-12-24,2021-12-17 15:20:57,2021-11-16 06:07:06,willian_m_s@hotmail.com,introduçãoaodeeplearning(parte2),0,2
79372,2679,Introdução ao Deep Learning (Parte 2),600,03:00,2021-11-17,2021-11-17,19:00,22:00,1970-01-01,1970-01-01,...,11835712754,21998083387,M,1987-09-26,2021-11-26 05:05:48,2021-11-16 12:57:19,antonio.canhota@talentify.io,introduçãoaodeeplearning(parte2),0,2

In [53]:
df1 = set_trilha(df1,df_ml_dl,trilhas["IAR"])
df1.shape

c:\Users\Talissa\Documents\env\ocean_bi_env\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

(73412, 29)

In [54]:
df_ml_ds = search_word(df1,"course_name","ciênciadedados")
df_ml_ds

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
7029,2335,Ciência de Dados: Visualização de Dados com Py...,300,02:00,2021-05-24,2021-05-24,16:00,18:00,2021-04-26,2021-05-24,...,16947233801,11982454553,M,1973-07-14,2021-12-17 15:01:02,NaN,luciano.tm@uol.com.br,ciênciadedados:visualizaçãodedadoscompython(pa...,0,1
7030,2335,Ciência de Dados: Visualização de Dados com Py...,300,02:00,2021-05-24,2021-05-24,16:00,18:00,2021-04-26,2021-05-24,...,88370992234,92981538181,M,1986-03-08,2021-06-01 22:48:27,2018-05-02 19:27:55,filhomarlon@hotmail.com,ciênciadedados:visualizaçãodedadoscompython(pa...,0,1
7031,2335,Ciência de Dados: Visualização de Dados com Py...,300,02:00,2021-05-24,2021-05-24,16:00,18:00,2021-04-26,2021-05-24,...,00894020226,92991454563,M,1992-10-19,2021-12-01 00:40:26,2018-06-29 02:49:34,nascimento.rodrigo@hotmail.com.br,ciênciadedados:visualizaçãodedadoscompython(pa...,0,1
7032,2335,Ciência de Dados: Visualização de Dados com Py...,300,02:00,2021-05-24,2021-05-24,16:00,18:00,2021-04-26,2021-05-24,...,22657434886,11985466144,M,1984-07-31,2021-11-05 17:11:25,2019-05-28 20:39:38,orleansklaus@gmail.com,ciênciadedados:visualizaçãodedadoscompython(pa...,0,1
7033,2335,Ciência de Dados: Visualização de Dados com Py...,300,02:00,2021-05-24,2021-05-24,16:00,18:00,2021-04-26,2021-05-24,...,38533792816,11984061040,M,1991-08-26,2021-10-01 01:31:45,NaN,aguiar.rafaelm@gmail.com,ciênciadedados:visualizaçãodedadoscompython(pa...,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87059,2754,Ciência de Dados: Fundamentos de Análise de Da...,600,03:00,2021-12-06,2021-12-06,18:00,21:00,2021-11-24,2021-12-06,...,2811323210,91980266717,M,1997-12-27,2021-12-20 15:30:51,2021-12-03 12:07:31,cfidalgo32@gmail.com,ciênciadedados:fundamentosdeanálisededadoscomo...,0,-
87060,2754,Ciência de Dados: Fundamentos de Análise de Da...,600,03:00,2021-12-06,2021-12-06,18:00,21:00,2021-11-24,2021-12-06,...,3525093179,61996380471,F,1996-02-21,2021-12-20 15:30:55,2021-12-03 16:31:01,marthinica.santiago@gmail.com,ciênciadedados:fundamentosdeanálisededadoscomo...,0,-
87061,2754,Ciência de Dados: Fundamentos de Análise de Da...,600,03:00,2021-12-06,2021-12-06,18:00,21:00,2021-11-24,2021-12-06,...,43918999220,(92) 98430-0622,M,1974-03-08,2021-12-03 17:37:16,2021-12-03 17:36:02,kramer.ti@hotmail.com,ciênciadedados:fundamentosdeanálisededadoscomo...,0,-
87062,2754,Ciência de Dados: Fundamentos de Análise de Da...,600,03:00,2021-12-06,2021-12-06,18:00,21:00,2021-11-24,2021-12-06,...,35409097882,11972717468,M,1994-04-13,2021-12-10 01:37:04,2021-12-04 14:45:52,valterclourenco@hotmail.com,ciênciadedados:fundamentosdeanálisededadoscomo...,0,-
87063,2754,Ciência de Dados: Fundamentos de Análise de Da...,600,03:00,2021-12-06,2021-12-06,18:00,21:00,2021-11-24,2021-12-06,...,74388959200,92981640025,M,1982-12-10,2021-12-07 14:00:03,2021-12-05 01:48:53,michael.trindade@hotmail.com,ciênciadedados:fundamentosdeanálisededadoscomo...,0,-

In [55]:
df1 = set_trilha(df1,df_ml_ds,trilhas["IAR"])
df1.shape

c:\Users\Talissa\Documents\env\ocean_bi_env\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

(73412, 29)

In [57]:
df_ml_org = search_word(df1,"course_name","orange")
df_ml_org

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
8908,2344,Ciência de Dados: Fundamentos de análise de da...,500,03:00,2021-05-28,2021-05-28,14:00,17:00,2021-04-26,2021-05-27,...,16947233801,11982454553,M,1973-07-14,2021-12-17 15:01:02,NaN,luciano.tm@uol.com.br,ciênciadedados:fundamentosdeanálisededadoscomo...,IAR,-
8909,2344,Ciência de Dados: Fundamentos de análise de da...,500,03:00,2021-05-28,2021-05-28,14:00,17:00,2021-04-26,2021-05-27,...,88370992234,92981538181,M,1986-03-08,2021-06-01 22:48:27,2018-05-02 19:27:55,filhomarlon@hotmail.com,ciênciadedados:fundamentosdeanálisededadoscomo...,IAR,-
8910,2344,Ciência de Dados: Fundamentos de análise de da...,500,03:00,2021-05-28,2021-05-28,14:00,17:00,2021-04-26,2021-05-27,...,22657434886,11985466144,M,1984-07-31,2021-11-05 17:11:25,2019-05-28 20:39:38,orleansklaus@gmail.com,ciênciadedados:fundamentosdeanálisededadoscomo...,IAR,-
8911,2344,Ciência de Dados: Fundamentos de análise de da...,500,03:00,2021-05-28,2021-05-28,14:00,17:00,2021-04-26,2021-05-27,...,38533792816,11984061040,M,1991-08-26,2021-10-01 01:31:45,NaN,aguiar.rafaelm@gmail.com,ciênciadedados:fundamentosdeanálisededadoscomo...,IAR,-
8912,2344,Ciência de Dados: Fundamentos de análise de da...,500,03:00,2021-05-28,2021-05-28,14:00,17:00,2021-04-26,2021-05-27,...,60311754287,9282041307,F,1977-09-17,2021-12-01 14:28:44,2019-07-05 14:49:22,nilmarasalgado@gmail.com,ciênciadedados:fundamentosdeanálisededadoscomo...,IAR,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87059,2754,Ciência de Dados: Fundamentos de Análise de Da...,600,03:00,2021-12-06,2021-12-06,18:00,21:00,2021-11-24,2021-12-06,...,2811323210,91980266717,M,1997-12-27,2021-12-20 15:30:51,2021-12-03 12:07:31,cfidalgo32@gmail.com,ciênciadedados:fundamentosdeanálisededadoscomo...,IAR,-
87060,2754,Ciência de Dados: Fundamentos de Análise de Da...,600,03:00,2021-12-06,2021-12-06,18:00,21:00,2021-11-24,2021-12-06,...,3525093179,61996380471,F,1996-02-21,2021-12-20 15:30:55,2021-12-03 16:31:01,marthinica.santiago@gmail.com,ciênciadedados:fundamentosdeanálisededadoscomo...,IAR,-
87061,2754,Ciência de Dados: Fundamentos de Análise de Da...,600,03:00,2021-12-06,2021-12-06,18:00,21:00,2021-11-24,2021-12-06,...,43918999220,(92) 98430-0622,M,1974-03-08,2021-12-03 17:37:16,2021-12-03 17:36:02,kramer.ti@hotmail.com,ciênciadedados:fundamentosdeanálisededadoscomo...,IAR,-
87062,2754,Ciência de Dados: Fundamentos de Análise de Da...,600,03:00,2021-12-06,2021-12-06,18:00,21:00,2021-11-24,2021-12-06,...,35409097882,11972717468,M,1994-04-13,2021-12-10 01:37:04,2021-12-04 14:45:52,valterclourenco@hotmail.com,ciênciadedados:fundamentosdeanálisededadoscomo...,IAR,-
87063,2754,Ciência de Dados: Fundamentos de Análise de Da...,600,03:00,2021-12-06,2021-12-06,18:00,21:00,2021-11-24,2021-12-06,...,74388959200,92981640025,M,1982-12-10,2021-12-07 14:00:03,2021-12-05 01:48:53,michael.trindade@hotmail.com,ciênciadedados:fundamentosdeanálisededadoscomo...,IAR,-

In [58]:
df1 = set_trilha(df1,df_ml_org,trilhas["IAR"])
df1.shape

c:\Users\Talissa\Documents\env\ocean_bi_env\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

(73412, 29)

In [64]:
df1.loc[df1.loc[:,"eve_trilha"]==0].eve_title.unique()

array(['Impressão e escaneamento 3D: métodos subtrativos e aditivos (Parte 4)',
       'Impressão e escaneamento 3D: métodos subtrativos e aditivos (Parte 1)',
       'Impressão e escaneamento 3D: métodos subtrativos e aditivos (Parte 2)',
       'Impressão e escaneamento 3D: métodos subtrativos e aditivos (Parte 3)',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC (Parte 1)',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC  (Parte 2)',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC  (Parte 3)',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC (Parte 4)',
       'Introdução a software de modelagem: Equipamento Corte a Laser/ Operação em Máquina CNC (Parte 5)'],
      dtype=object)

Trilha FABLAB

In [66]:
df_fab = search_word(df1,"course_name","impressão|CNC")
df_fab

,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,eve_enrollment_end,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
61169,2578,Impressão e escaneamento 3D: métodos subtrativ...,21,02:00,2021-10-19,2021-10-19,14:00,16:00,1970-01-01,1970-01-01,...,00023572248,92994360562,M,1990-09-25,2021-11-08 20:28:03,NaN,wellingtonlnilo@gmail.com,impressãoeescaneamento3d:métodossubtrativosead...,0,3
61170,2578,Impressão e escaneamento 3D: métodos subtrativ...,21,02:00,2021-10-19,2021-10-19,14:00,16:00,1970-01-01,1970-01-01,...,88988104234,92994301486,M,1989-07-11,2021-11-08 20:28:03,2019-05-16 20:41:54,israelsimukaua7@gmail.com,impressãoeescaneamento3d:métodossubtrativosead...,0,3
61171,2578,Impressão e escaneamento 3D: métodos subtrativ...,21,02:00,2021-10-19,2021-10-19,14:00,16:00,1970-01-01,1970-01-01,...,03142932216,92994116056,M,2000-01-31,2021-12-20 15:30:58,2018-09-21 13:52:54,vaf.eai18@uea.edu.br,impressãoeescaneamento3d:métodossubtrativosead...,0,3
61172,2578,Impressão e escaneamento 3D: métodos subtrativ...,21,02:00,2021-10-19,2021-10-19,14:00,16:00,1970-01-01,1970-01-01,...,51128900297,92991025250,M,1980-04-19,2021-11-08 20:28:03,NaN,vandersons@gmail.com,impressãoeescaneamento3d:métodossubtrativosead...,0,3
61173,2578,Impressão e escaneamento 3D: métodos subtrativ...,21,02:00,2021-10-19,2021-10-19,14:00,16:00,1970-01-01,1970-01-01,...,05573803166,92994337438,M,1997-06-14,2021-12-09 20:14:24,2019-03-19 02:53:10,hbueno150@gmail.com,impressãoeescaneamento3d:métodossubtrativosead...,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80337,2685,Introdução a software de modelagem: Equipament...,15,02:00,2021-11-19,2021-11-19,14:00,16:00,1970-01-01,1970-01-01,...,60350890200,92992675216,M,1977-05-23,2021-11-30 17:21:22,2021-06-29 18:24:05,davidborges2305@gmail.com,introduçãoasoftwaredemodelagem:equipamentocort...,0,5
80338,2685,Introdução a software de modelagem: Equipament...,15,02:00,2021-11-19,2021-11-19,14:00,16:00,1970-01-01,1970-01-01,...,2011960266,92992111962,M,2001-11-25,2021-11-30 17:21:22,2021-08-18 10:20:30,lbp.eng20@uea.edu.br,introduçãoasoftwaredemodelagem:equipamentocort...,0,5
80339,2685,Introdução a software de modelagem: Equipament...,15,02:00,2021-11-19,2021-11-19,14:00,16:00,1970-01-01,1970-01-01,...,70405507259,92993660318,M,2001-06-22,2021-12-14 03:23:41,2021-09-01 13:38:34,icarocpbjm@gmail.com,introduçãoasoftwaredemodelagem:equipamentocort...,0,5
80340,2685,Introdução a software de modelagem: Equipament...,15,02:00,2021-11-19,2021-11-19,14:00,16:00,1970-01-01,1970-01-01,...,3343255289,92992800606,M,2002-07-17,2021-11-30 17:21:22,2021-09-02 17:39:05,acsds.snf21@uea.edu.br,introduçãoasoftwaredemodelagem:equipamentocort...,0,5
80341,2685,Introdução a software de modelagem: Equipament...,15,02:00,2021-11-19,2021-11-19,14:00,16:00,1970-01-01,1970-01-01,...,1522988270,92988365246,F,1995-05-12,2021-12-01 00:40:31,2021-09-02 20:49:23,dayanaalmeida12@hotmail.com,introduçãoasoftwaredemodelagem:equipamentocort...,0,5

In [69]:
df1 = set_trilha(df1,df_fab,trilhas["FABLAB"])
df1.shape

c:\Users\Talissa\Documents\env\ocean_bi_env\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

(73412, 29)

In [70]:
df1.groupby(["eve_trilha"]).size()

eve_trilha
AND       11115
BCKEND     6924
BLC        2834
BXB         709
FABLAB      175
FRTEND     4434
GME        6194
IAR       15824
IOT        5481
PRG       16042
TZN         661
WRB         442
ÁGIL       2577
dtype: int64

In [71]:
df1.to_csv("cursos_ofertados_2_ano_com_trilha.csv")

c:\Users\Talissa\Documents\env\ocean_bi_env\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (20) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Unnamed: 0,eve_id,eve_title,eve_vacancy,eve_workload,eve_start_date,eve_end_date,eve_start_hour,eve_end_hour,eve_enrollment_start,...,stu_cpf,stu_phone,stu_gender,stu_birth_date,stu_creation_date,stu_last_login,stu_email,course_name,eve_trilha,is_session
0,0,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,...,22657434886,11985466144,M,1984-07-31,2021-10-01 18:04:15,2019-05-28 20:39:38,orleansklaus@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
1,1,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,...,38533792816,11984061040,M,1991-08-26,2021-10-01 01:31:45,NaN,aguiar.rafaelm@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
2,2,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,...,89609034268,92991015108,M,1986-05-16,2021-05-14 00:14:44,NaN,anglops@gmail.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
3,3,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,...,00289630240,92991551517,M,1989-11-09,2021-08-17 23:45:03,NaN,gerson.cunha@outlook.com,tizen:ferramentaeambientededesenvolvimento,TZN,-
4,4,2296,Tizen: Ferramenta e Ambiente de Desenvolvimento,500,01:30,2021-04-23,2021-04-23,17:00,18:30,2021-03-19,...,01603746269,92984041284,M,1997-08-21,2021-05-10 20:30:46,2019-02-20 08:02:28,gqs.snf17@uea.edu.br,tizen:ferramentaeambientededesenvolvimento,TZN,-